import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, AlertTriangle, CheckCircle2, Search, FileCog } from 'lucide-react';
import { ArchiveScanner, ScanResult } from '../../services/ArchiveScanner';
import { DOSSIER_LIBRARY, DossierFile } from '../../data/knowledge/DossierLibrary';
import { GlassCard } from '../../shared/components/ui/GlassCard';

export const DossierViewer: React.FC = () => {
    const [scanResult, setScanResult] = useState<ScanResult | null>(null);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState('');

    useEffect(() => {
        const load = async () => {
            setLoading(true);
            const result = await ArchiveScanner.scanDocs();
            setScanResult(result);
            setLoading(false);
        };
        load();
    }, []);

    const getFileStatus = (path: string) => {
        if (!scanResult) return 'UNKNOWN';
        return scanResult.details.find(d => d.path === path)?.status || 'UNKNOWN';
    };

    const handleGenerateTemplate = (file: DossierFile) => {
        // Logic to generate a template or download a starter
        const content = `ENGINEERING DOSSIER TEMPLATE\n\nTitle: ${file.path.split('/').pop()}\nCategory: ${file.category}\nJustification: ${file.justification}\n\n[IEC 60041 COMPLIANT STRUCTURE]\n1. Scope\n2. References\n3. Terms and Definitions\n4. Methodology\n5. Results\n\n-- GENERATED BY MONOLIT OS --`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `TEMPLATE_${file.path.split('/').pop() || 'dossier'}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const filteredLibrary = DOSSIER_LIBRARY.filter(f =>
        f.path.toLowerCase().includes(filter.toLowerCase()) ||
        f.category.toLowerCase().includes(filter.toLowerCase())
    );

    return (
        <div className="p-6 space-y-6">
            <div className="flex flex-col md:flex-row justify-between items-end gap-4 border-b border-white/10 pb-4">
                <div>
                    <h2 className="text-2xl font-black text-white uppercase tracking-tighter flex items-center gap-3">
                        <FileCog className="w-6 h-6 text-cyan-400" />
                        50 Hardened Engineering Dossiers
                    </h2>
                    <div className="flex items-center gap-4 mt-2">
                        <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
                            PROTOCOL NC-12 // SHADOW VAULT
                        </span>
                        {!loading && scanResult && (
                            <span className="text-[10px] font-black font-mono text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                                {scanResult.verifiedFiles} / {scanResult.totalFiles} VERIFIED
                            </span>
                        )}
                    </div>
                </div>

                <div className="relative group w-full md:w-64">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500 group-focus-within:text-cyan-400 transition-colors" />
                    <input
                        type="text"
                        placeholder="SEARCH_VAULT..."
                        value={filter}
                        onChange={(e) => setFilter(e.target.value)}
                        className="w-full bg-black/20 border border-white/10 rounded-lg py-2 pl-9 pr-4 text-xs font-mono text-slate-300 focus:outline-none focus:border-cyan-500/50 focus:bg-black/40 transition-all placeholder:text-slate-600"
                    />
                </div>
            </div>

            {loading ? (
                <div className="flex flex-col items-center justify-center h-64 space-y-4">
                    <div className="w-12 h-12 border-4 border-cyan-500/20 border-t-cyan-500 rounded-full animate-spin" />
                    <span className="text-xs font-mono text-cyan-500 animate-pulse">SCANNING_PHYSICAL_ARCHIVE...</span>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    <AnimatePresence>
                        {filteredLibrary.map((file, idx) => {
                            const status = getFileStatus(file.path);
                            const isMissing = status === 'MISSING';

                            return (
                                <motion.div
                                    key={file.path}
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: idx * 0.02 }}
                                >
                                    <GlassCard className={`h-full flex flex-col justify-between group hover:border-white/20 transition-all ${isMissing ? 'border-red-500/20 bg-red-500/5' : 'border-emerald-500/10'}`}>
                                        <div className="mb-4">
                                            <div className="flex justify-between items-start mb-2">
                                                <span className={`text-[8px] font-black uppercase tracking-wider px-1.5 py-0.5 rounded ${isMissing ? 'bg-red-500/20 text-red-400' : 'bg-cyan-500/10 text-cyan-400'}`}>
                                                    {file.category}
                                                </span>
                                                {isMissing ? (
                                                    <AlertTriangle className="w-4 h-4 text-red-500" />
                                                ) : (
                                                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                                )}
                                            </div>
                                            <h3 className="text-xs font-bold text-slate-200 leading-snug break-all font-mono">
                                                {file.path.split('/').pop()}
                                            </h3>
                                            <p className="text-[10px] text-slate-500 mt-2 line-clamp-2">
                                                {file.justification}
                                            </p>
                                        </div>

                                        <div className="pt-3 border-t border-white/5">
                                            {isMissing ? (
                                                <button
                                                    onClick={() => handleGenerateTemplate(file)}
                                                    className="w-full py-1.5 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 rounded flex items-center justify-center gap-2 transition-all text-[9px] font-black uppercase tracking-wider"
                                                >
                                                    <Download className="w-3 h-3" />
                                                    Generate Template
                                                </button>
                                            ) : (
                                                <a
                                                    href={file.path}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="w-full py-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded flex items-center justify-center gap-2 transition-all text-[9px] font-black uppercase tracking-wider"
                                                >
                                                    <FileText className="w-3 h-3" />
                                                    Open Dossier
                                                </a>
                                            )}
                                        </div>
                                    </GlassCard>
                                </motion.div>
                            );
                        })}
                    </AnimatePresence>
                </div>
            )}
        </div>
    );
};
