-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PLANTS TABLE
create table if not exists plants (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  location_name text not null,
  gps_lat numeric,
  gps_lng numeric,
  elevation_masl numeric default 0,
  ambient_temp_avg numeric default 20,
  humidity_avg numeric default 50,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. ASSETS TABLE
-- Note: Using bigint for id to maintain compatibility with existing frontend code (AssetContext expects numbers)
create table if not exists assets (
  id bigint generated by default as identity primary key,
  plant_id uuid references plants(id),
  name text not null,
  type text not null default 'HPP',
  location text,
  lat numeric,
  lng numeric,
  power_output numeric, -- mapped to capacity
  status text default 'Operational',
  turbine_type text,
  specs jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. HYDROLOGY_CONTEXT TABLE
create table if not exists hydrology_context (
  id uuid default uuid_generate_v4() primary key,
  plant_id uuid references plants(id),
  gross_head_m numeric,
  design_flow_cms numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. PRICING_HISTORY TABLE
create table if not exists pricing_history (
  id uuid default uuid_generate_v4() primary key,
  asset_id bigint references assets(id),
  effective_from timestamp with time zone default now(),
  price_per_kwh numeric,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. PRODUCTION_FORECAST TABLE
create table if not exists production_forecast (
  id uuid default uuid_generate_v4() primary key,
  asset_id bigint references assets(id),
  forecast_date timestamp with time zone not null,
  energy_mwh numeric not null,
  confidence numeric default 0.9, -- 0 to 1
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. DISABLE RLS (Public Access for Demo)
alter table plants enable row level security;
alter table assets enable row level security;
alter table hydrology_context enable row level security;
alter table pricing_history enable row level security;
alter table production_forecast enable row level security;

-- Create policies for public access
create policy "Enable read access for all users" on plants for select using (true);
create policy "Enable insert access for all users" on plants for insert with check (true);
create policy "Enable update access for all users" on plants for update using (true);

create policy "Enable read access for all users" on assets for select using (true);
create policy "Enable insert access for all users" on assets for insert with check (true);
create policy "Enable update access for all users" on assets for update using (true);

create policy "Enable read access for all users" on hydrology_context for select using (true);
create policy "Enable insert access for all users" on hydrology_context for insert with check (true);
create policy "Enable update access for all users" on hydrology_context for update using (true);

create policy "Enable read access for all users" on pricing_history for select using (true);
create policy "Enable insert access for all users" on pricing_history for insert with check (true);
create policy "Enable update access for all users" on pricing_history for update using (true);

create policy "Enable read access for all users" on production_forecast for select using (true);
create policy "Enable insert access for all users" on production_forecast for insert with check (true);
create policy "Enable update access for all users" on production_forecast for update using (true);
