-- SUPABASE RLS DISABLE SCRIPT
-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO FIX 401/404 ERRORS

-- 1. Disable Row Level Security (RLS) on all tables to allow public access (for development/educational use)
ALTER TABLE IF EXISTS "public"."assets" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."asset_maintenance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."asset_telemetry" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."audit_logs" DISABLE ROW LEVEL SECURITY;

-- 2. Create tables if they don't exist (Idempotent)
CREATE TABLE IF NOT EXISTS "public"."assets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "location" TEXT,
    "coordinates" JSONB,
    "capacity_mw" NUMERIC,
    "status" TEXT DEFAULT 'Operational',
    "specs" JSONB,
    "last_maintenance" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "public"."asset_telemetry" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "asset_id" BIGINT REFERENCES "public"."assets"("id"),
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "metrics" JSONB
);

CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "action" TEXT NOT NULL,
    "details" JSONB,
    "user_id" UUID
);

-- 3. Grant usage on schema public to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 4. Verify Policy Removal
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."assets";
DROP POLICY IF EXISTS "Enable insert access for all users" ON "public"."assets";
DROP POLICY IF EXISTS "Enable update access for all users" ON "public"."assets";

-- 5. Insert Dummy Data if Empty
INSERT INTO "public"."assets" ("name", "type", "location", "capacity_mw", "status", "specs")
SELECT 'Test Francis Unit 1', 'FRANCIS', 'Alpine Region', 45.5, 'Operational', '{"ratedHead": 120, "flow": 45}'
WHERE NOT EXISTS (SELECT 1 FROM "public"."assets" LIMIT 1);
