export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    MAINTENANCE: {
        ROOT: 'maintenance',
        DASHBOARD: 'dashboard',
        LOGBOOK: 'logbook',
        HYDRAULIC: 'hydraulic',
        BOLT_TORQUE: 'bolt-torque',
        SHADOW_ENGINEER: 'shadow-engineer', // SOPManager
        INTUITION_LOG: 'intuition-log', // ShiftLog
        AR_GUIDE: 'ar-guide', // ARManager
        EXECUTIVE: 'executive',
    },
    FRANCIS: {
        ROOT: 'francis',
        HUB: 'hub',
        DIAGNOSTICS: 'diagnostics',
        MISSION_CONTROL: 'mission-control',
        EMERGENCY: 'emergency-protocols',
        LOGIC_LOAD_REJECTION: 'logic-load-rejection',
        FLOWCHART_STARTUP: 'flowchart-startup',
        SOP: {
            WATER_HAMMER: 'sop-water-hammer',
            BEARINGS: 'sop-bearings',
            ALIGNMENT: 'sop-shaft-alignment',
            THRUST_BALANCE: 'sop-thrust-balance',
            VORTEX_CONTROL: 'sop-vortex-control',
            MIV_DISTRIBUTOR: 'sop-miv-distributor',
            REGULATING_RING: 'sop-regulating-ring',
            LINKAGE: 'sop-linkage',
            COUPLING: 'sop-coupling',
            BRAKING_SYSTEM: 'sop-braking-system',
            SEAL_RECOVERY: 'sop-recovery',
            OIL_HEALTH: 'sop-oil-health',
            COOLING_WATER: 'sop-cooling-water',
            DRAINAGE_PUMPS: 'sop-drainage-pumps',
            LUBRICATION: 'sop-lubrication',
            HPU: 'sop-hpu',
            GENERATOR: 'sop-generator-integrity',
            ELECTRICAL_HEALTH: 'sop-electrical-health',
            GOVERNOR_PID: 'sop-governor-pid',
            GRID_SYNC: 'sop-grid-sync',
            DISTRIBUTOR_SYNC: 'sop-distributor-sync',
            DC_SYSTEMS: 'sop-dc-systems',
            EXCITATION: 'sop-excitation',
            TRANSFORMER: 'sop-transformer',
            PENSTOCK: 'sop-penstock',
            INTAKE: 'sop-intake',
            CATHODIC: 'sop-cathodic',
            AUXILIARY: 'sop-auxiliary',
        }
    },
    // Add other high level routes
    MAP: 'map',
    PROFILE: 'profile',
    RISK_ASSESSMENT: 'risk-assessment',
} as const;
