import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { robotoBase64 } from '../utils/fonts/Roboto-Regular-base64';
import { TFunction } from 'i18next';

/**
 * Unified PDF Service for AnoHUB
 * Enforces brand consistency and centralized document generation logic.
 */
export class PdfService {

    /**
     * initializes a new jsPDF document with standard fonts
     */
    private static createDoc(): jsPDF {
        const doc = new jsPDF();
        try {
            if (robotoBase64 && robotoBase64.length > 100) {
                doc.addFileToVFS("Roboto-Regular.ttf", robotoBase64);
                doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
                doc.setFont("Roboto");
            } else {
                console.warn("PdfService: Roboto Base64 invalid. Fallback into Helvetica");
                doc.setFont("helvetica");
            }
        } catch (e) {
            console.error("PdfService: Error loading font", e);
            doc.setFont("helvetica");
        }
        return doc;
    }

    /**
     * Applies the standard AnoHUB Header
     */
    private static applyHeader(doc: jsPDF, title: string, subtitle?: string) {
        const pageWidth = doc.internal.pageSize.width;

        // Dark Slate Background
        doc.setFillColor(15, 23, 42);
        doc.rect(0, 0, pageWidth, 35, 'F');

        // Brand Name / Logo Placeholder
        doc.setTextColor(34, 211, 238); // Cyan
        doc.setFontSize(22);
        doc.setFont('Roboto', 'normal');
        doc.text("ANOHUB ENGINEERING", 20, 18);

        // Dynamic Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(10);
        doc.text(title.toUpperCase(), pageWidth - 20, 15, { align: 'right' });

        if (subtitle) {
            doc.setTextColor(148, 163, 184); // Slate 400
            doc.text(subtitle, pageWidth - 20, 25, { align: 'right' });
        }
    }

    /**
     * Applies the standard Footer with Page Numbers
     */
    private static applyFooter(doc: jsPDF) {
        const pageCount = (doc as any).internal.getNumberOfPages();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;

        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(100, 116, 139); // Slate 500

            // Left: System ID
            doc.text(`SYS-ID: ${new Date().getTime().toString(36).toUpperCase()}`, 20, pageHeight - 10);

            // Center: Branding
            doc.text("Generated by AnoHUB Platform V2.5", pageWidth / 2, pageHeight - 10, { align: 'center' });

            // Right: Page Number
            doc.text(`${i} / ${pageCount}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
        }
    }

    /**
     * Generates a comprehensive Audit Report Snapshot
     */
    public static generateAuditReport(
        contextTitle: string,
        slogan: string,
        metrics: any[],
        diagnostics: any[],
        logs: any[],
        engineerName: string,
        t: TFunction
    ): Blob {
        const doc = this.createDoc();
        const pageWidth = doc.internal.pageSize.width;

        // Header
        this.applyHeader(doc, "Audit Report", new Date().toLocaleString());

        // Context Section
        let y = 50;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(18);
        doc.text(contextTitle.toUpperCase(), 20, y);
        doc.setDrawColor(34, 211, 238);
        doc.line(20, y + 2, pageWidth - 20, y + 2);

        y += 10;
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        doc.setFont('Roboto', 'italic');
        doc.text(`"${slogan}"`, 20, y);
        doc.setFont('Roboto', 'normal');

        // 1. Live Metrics
        y += 15;
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text(t('sidebar.analytics.liveSnapshot', "Live Context Snapshot"), 20, y);
        y += 8;

        if (metrics && metrics.length > 0) {
            const tableData = metrics.map((m: any) => [
                m.label,
                `${typeof m.value === 'number' ? m.value.toFixed(2) : m.value} ${m.unit}`,
                m.status === 'critical' ? 'CRITICAL' : m.status === 'warning' ? 'WARNING' : 'NOMINAL'
            ]);

            autoTable(doc, {
                startY: y,
                head: [[t('common.metric', "Metric"), t('common.value', "Value"), t('common.status', "Status")]],
                body: tableData,
                headStyles: { fillColor: [15, 23, 42], textColor: [34, 211, 238] },
                alternateRowStyles: { fillColor: [241, 245, 249] }
            });
            y = (doc as any).lastAutoTable.finalY + 15;
        } else {
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text("No live metrics available.", 20, y);
            y += 15;
        }

        // 2. Diagnostics
        if (diagnostics && diagnostics.length > 0) {
            doc.setFontSize(14);
            doc.setTextColor(15, 23, 42);
            doc.text(t('sidebar.analytics.diagnostics', "Active Engineering Insights"), 20, y);
            y += 8;

            diagnostics.forEach((diag: any) => {
                doc.setFillColor(diag.type === 'critical' ? 254 : 255, 242, 242);
                doc.rect(20, y, pageWidth - 40, 15, 'F');
                doc.setDrawColor(200, 200, 200);
                doc.rect(20, y, pageWidth - 40, 15, 'S');

                doc.setFontSize(10);
                doc.setTextColor(0, 0, 0);
                doc.text(`${diag.type === 'critical' ? 'CRITICAL' : 'INFO'}: ${diag.messageKey || diag.message}`, 25, y + 9);
                y += 18;
            });
            y += 10;
        }

        // 3. Log History
        if (logs && logs.length > 0) {
            // Check page break
            if (y > doc.internal.pageSize.height - 40) {
                doc.addPage();
                y = 40;
            }

            doc.setFontSize(14);
            doc.setTextColor(15, 23, 42);
            doc.text(t('sidebar.analytics.history', "Recent Activity"), 20, y);
            y += 8;

            const logData = logs.map((l: any) => [
                new Date(l.timestamp).toLocaleDateString(),
                l.technician,
                l.summaryDE || l.commentBS || "Log Entry"
            ]);

            autoTable(doc, {
                startY: y,
                head: [[t('pdf.passport.date'), t('pdf.passport.user'), t('pdf.passport.action')]],
                body: logData,
                headStyles: { fillColor: [71, 85, 105], textColor: [255, 255, 255] }
            });
        }

        this.applyFooter(doc);
        return doc.output('blob');
    }
}
