/**
 * AssetIdentity Types
 * Complete Digital Twin Foundation Schema
 */

export type TurbineType = 'PELTON' | 'KAPLAN' | 'FRANCIS' | 'CROSSFLOW';
export type TurbineFamily = TurbineType;
export type Orientation = 'VERTICAL' | 'HORIZONTAL';
export type TransmissionType = 'DIRECT' | 'GEARBOX';
export type PenstockMaterial = 'CONCRETE' | 'STEEL' | 'PLASTIC' | 'FRP';
export type WaterAbrasivity = 'LOW' | 'MEDIUM' | 'HIGH' | 'EXTREME';
export type SealType = 'METALLIC' | 'COMPOSITE';
export type SensorType = 'ACCELEROMETER' | 'VELOCITY' | 'DISPLACEMENT' | 'RTD' | 'THERMOCOUPLE' | 'INFRARED';
export type MountingType = 'PERMANENT' | 'MAGNETIC' | 'STUD';
export type MeasurementAxis = 'RADIAL' | 'AXIAL' | 'TANGENTIAL' | '3-AXIS';
export type UpgradeCategory = 'VIBRATION' | 'TEMPERATURE' | 'PRESSURE' | 'FLOW';
export type UpgradePriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type ComplianceStatus = 'COMPLIANT' | 'NON_COMPLIANT';
export type CleanerType = 'AUTOMATIC' | 'MANUAL' | 'NONE';

// ==================== MACHINE CONFIGURATION ====================

export interface MachineConfiguration {
    orientation: Orientation;
    transmissionType: TransmissionType;

    // Basic Ratings
    ratedPowerMW: number;
    ratedSpeedRPM: number;
    ratedHeadM: number;
    ratedFlowM3S: number;

    // Mechanical Details
    runnerDiameterMM: number;
    numberOfBlades: number;
    numberOfGuidVanes?: number;

    // Gearbox (if applicable)
    gearboxRatio?: number;
    gearboxManufacturer?: string;
    gearboxType?: string;  // "Planetary", "Helical"
}

// ==================== SHAFT JACKING MODULE ====================

export interface ShaftJackingModule {
    enabled: boolean;

    // Operating Parameters
    systemPressureBar: number;
    systemFlowLPM: number;
    liftingDistance001MM: number;  // In 0.01mm units

    // Timing
    jackingDurationSeconds: number;
    minimumJackingPressureBar: number;

    // Sensors
    pressureSensorInstalled: boolean;
    flowSensorInstalled: boolean;
    positionSensorInstalled: boolean;

    // Maintenance
    lastServiceDate?: string;
    nextServiceDue?: string;
}

// ==================== SPECIALIZED ADVANCED MODULE ====================

export interface SpecializedAdvancedModule {
    // Runner Clearances
    frontRunnerClearanceMM: number;
    backRunnerClearanceMM: number;
    spiralClearanceMM: number;

    // Labyrinth Seals
    labyrinthGaps: {
        upperLabyrinthMM: number;
        lowerLabyrinthMM: number;
        sealType: SealType;
    };

    // Pressure Monitoring
    draftTubePressure: {
        nominalBar: number;
        minBar: number;
        maxBar: number;
        sensorInstalled: boolean;
    };

    backRunnerPressure: {
        nominalBar: number;
        minBar: number;
        maxBar: number;
        sensorInstalled: boolean;
    };

    // Auto-calculated
    axialThrustBalanced: boolean;
    pressureDifferenceBar: number;
}

// ==================== SENSOR MATRIX ====================

export interface VibrationSensor {
    id: string;
    location: string;
    sensorType: SensorType;
    installed: boolean;
    mountingType?: MountingType;
    measurementAxis?: MeasurementAxis;
}

export interface TemperatureSensor {
    id: string;
    location: string;
    sensorType: SensorType;
    installed: boolean;
    rangeMinC: number;
    rangeMaxC: number;
}

export interface PressureSensor {
    id: string;
    location: string;
    installed: boolean;
    rangeMinBar: number;
    rangeMaxBar: number;
}

export interface UpgradeRecommendation {
    id: string;
    category: UpgradeCategory;
    priority: UpgradePriority;
    title: string;
    description: string;
    estimatedCostEUR: number;
    roi: string;
    autoGenerated: boolean;
}

export interface SensorMatrix {
    vibrationSensors: {
        generator: VibrationSensor[];
        turbine: VibrationSensor[];
        gearbox?: VibrationSensor[];
    };

    temperatureSensors: {
        bearings: TemperatureSensor[];
        oilSystem: TemperatureSensor[];
        powerhouse: TemperatureSensor[];
    };

    pressureSensors: PressureSensor[];

    upgradeRecommendations: UpgradeRecommendation[];
}

// ==================== HPU & FLUID INTELLIGENCE ====================

export interface FluidIntelligence {
    oilSystem: {
        oilType: string;
        oilCapacityLiters: number;
        currentHours: number;
        changeIntervalHours: number;
        lastChangeDate: string;
        nextChangeDue: string;
        waterContentPPM?: number; // ppm
        tan?: number;           // mgKOH/g
        viscosityCSt?: number;  // cSt @ 40C
    };

    filterSystem: {
        filterType: string;
        installDate: string;
        deltaPBar: number;
        deltaPAlarmBar: number;
        filterClogged: boolean;
    };

    temperatureCorrelation: {
        powerhouseAmbientC: number;
        bearingTempsC: number[];
        excessiveHeatDetected: boolean;
    };

    healthScore: number;  // 0-100
}

// ==================== ENVIRONMENTAL BASELINE ====================

export interface EnvironmentalBaseline {
    noiseLevel: {
        operatingDB: number;
        locations: {
            powerhouse: number;
            turbinePit: number;
            controlRoom: number;
        };
        regulatoryLimitDB: number;
        complianceStatus: ComplianceStatus;
    };

    ambientTemperature: number; // Grad C
    relativeHumidity: number;    // %

    penstockType: PenstockMaterial;
    penstockDiameterMM: number;
    penstockLengthM: number;
    penstockThicknessMM: number;

    sludgeRemoval: {
        hasSludgeCleaner: boolean;
        cleanerType?: CleanerType;
        cleaningFrequencyDays?: number;
        erosionRiskScore: number;  // 0-10
    };

    waterQuality: {
        sedimentContentMGL: number;
        abrasivityIndex: WaterAbrasivity;
        phLevel: number;
    };
}

// ==================== OPERATIONAL MAPPING ====================

export interface OperatingPoint {
    timestamp: string;
    vaneOpeningPercent: number;
    activePowerMW: number;
    headM: number;
    flowM3S: number;
    efficiency?: number;
}

export interface OperationalMapping {
    operatingPoints: OperatingPoint[];
    currentPoint: OperatingPoint | null;

    hillChart: {
        dataPoints: number;
        coveragePercent: number;
        lastUpdated: string;
    };

    bestEfficiencyPoint: {
        vaneOpeningPercent: number;
        activePowerMW: number;
        efficiency: number;
    } | null;
}

// ==================== MAIN ASSET IDENTITY ====================

export interface AssetIdentity {
    // Basic Info
    assetId: string;
    assetName: string;
    turbineType: TurbineType;
    manufacturer: string;
    commissioningYear: number;
    totalOperatingHours: number;
    hoursSinceLastOverhaul: number;
    startStopCount: number;
    lastMajorOverhaul?: string;
    lastAlignmentDate?: string;
    location: string;

    // Configuration
    machineConfig: MachineConfiguration;

    // Conditional Modules
    specializedAdvanced?: SpecializedAdvancedModule;
    shaftJacking?: ShaftJackingModule;

    // Core Modules
    sensorMatrix: SensorMatrix;
    fluidIntelligence: FluidIntelligence;
    environmentalBaseline: EnvironmentalBaseline;
    operationalMapping: OperationalMapping;

    // Metadata
    createdAt: string;
    createdBy: string;
    lastUpdatedAt: string;
    version: string;
}
