import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// PUTANJE: Izlazimo iz 'utils' (..) direktno u 'src' gdje su types i constants
import type { VerificationData, ProtocolSection, Answers, OperationalData, HPPSettings, TurbineRecommendation } from '../types.ts';
import { QUESTIONS } from '../constants.ts'; 

// --- HELPER: COMMON HEADER ---
const addHeader = (doc: jsPDF, title: string) => {
    const date = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();

    doc.setFontSize(22);
    doc.setTextColor(6, 182, 212); // AnoHUB Cyan
    doc.text('AnoHUB', 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Strategic Risk Mitigation & Asset Integrity', 14, 25);

    doc.setDrawColor(6, 182, 212);
    doc.line(14, 28, 196, 28); 

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text(title, 14, 40);

    doc.setFontSize(11);
    doc.text(`Date: ${date} ${time}`, 14, 48);
    return 55; 
};

const addFooter = (doc: jsPDF) => {
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by AnoHUB Platform - Hydro-Immunity Protocol.', 14, pageHeight - 10);
};

// --- 1. INSTALLATION REPORT ---
export const generateInstallationReport = (
    progress: Record<string, VerificationData>,
    riskScore: number,
    protocols: ProtocolSection[]
) => {
    const doc = new jsPDF();
    let startY = addHeader(doc, 'INSTALLATION VERIFICATION REPORT');
    
    doc.text('Discipline Risk Score:', 14, startY);
    doc.setFontSize(14);
    if (riskScore > 0) {
        doc.setTextColor(220, 38, 38); 
        doc.text(`${riskScore} (CRITICAL RISK)`, 60, startY);
    } else {
        doc.setTextColor(22, 163, 74); 
        doc.text(`${riskScore} (OPTIMAL)`, 60, startY);
    }

    const tableRows: any[] = [];
    if (protocols) {
         // @ts-ignore
        const sections = Array.isArray(protocols) ? protocols : [protocols];
        sections.forEach((section: any) => {
            if(section.steps) {
                section.steps.forEach((step: any) => {
                    const data = progress[step.id];
                    if (data) {
                        tableRows.push([
                            step.id,
                            step.title,
                            data.status.toUpperCase(),
                            data.value || '-',
                            data.comment || '-',
                            data.logbookConfirmed ? 'YES' : 'NO'
                        ]);
                    }
                });
            }
        });
    }

    if (tableRows.length === 0) {
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text('No verification data recorded.', 14, startY + 15);
    } else {
        autoTable(doc, {
            startY: startY + 10,
            head: [['ID', 'Step', 'Status', 'Value', 'Observation', 'Logbook']],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: [15, 23, 42], textColor: [6, 182, 212], fontStyle: 'bold' },
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: {
                0: { cellWidth: 15 }, 
                2: { cellWidth: 20, fontStyle: 'bold' }, 
                5: { cellWidth: 15 } 
            },
            didParseCell: function(data) {
                if (data.section === 'body' && data.column.index === 2) {
                    const text = data.cell.raw as string;
                    if (text === 'FAILED') data.cell.styles.textColor = [220, 38, 38];
                    else if (text === 'VERIFIED') data.cell.styles.textColor = [22, 163, 74];
                }
            }
        });
    }

    const finalY = (doc as any).lastAutoTable?.finalY || 80;
    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.text('Verified by (Signature): __________________________', 14, finalY + 20);

    addFooter(doc);
    doc.save(`AnoHUB_Install_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};

// --- 2. RISK ASSESSMENT REPORT ---
export const generateRiskReport = (
    answers: Answers,
    operationalData: OperationalData,
    riskLevel: { text: string, color: string },
    description: string
) => {
    const doc = new jsPDF();
    let startY = addHeader(doc, 'HPP RISK ASSESSMENT REPORT');

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('Operational Parameters:', 14, startY);
    
    doc.setFontSize(10);
    doc.setTextColor(80);
    const opY = startY + 8;
    
    doc.text(`Head: ${operationalData?.head || '-'} m`, 14, opY);
    doc.text(`Flow: ${operationalData?.flow || '-'} m3/s`, 60, opY);
    doc.text(`Pressure: ${operationalData?.pressure || '-'} bar`, 110, opY);
    doc.text(`Output: ${operationalData?.output || '-'} MW`, 160, opY);

    const riskY = opY + 15;
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('Calculated Execution Gap Risk:', 14, riskY);
    
    doc.setFontSize(14);
    if (riskLevel.text.includes('High')) doc.setTextColor(220, 38, 38);
    else if (riskLevel.text.includes('Medium')) doc.setTextColor(234, 179, 8);
    else doc.setTextColor(22, 163, 74);
    
    doc.text(riskLevel.text.toUpperCase(), 80, riskY);

    const tableRows: any[] = [];
    QUESTIONS.forEach(q => {
        const answer = answers[q.id];
        if (answer) {
            tableRows.push([
                q.id.toUpperCase(),
                q.text,
                answer
            ]);
        }
    });

    autoTable(doc, {
        startY: riskY + 10,
        head: [['ID', 'Diagnostic Question', 'Observed Status']],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: [15, 23, 42], textColor: [250, 204, 21] },
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 15, fontStyle: 'bold' },
            1: { cellWidth: 110 },
            2: { cellWidth: 60, fontStyle: 'bold' }
        }
    });

    let finalY = (doc as any).lastAutoTable?.finalY || 150;
    
    if (description) {
        if (finalY > 250) { doc.addPage(); finalY = 20; }
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text('Additional Engineer Observations:', 14, finalY + 10);
        
        doc.setFontSize(10);
        doc.setTextColor(60);
        const splitText = doc.splitTextToSize(description, 180);
        doc.text(splitText, 14, finalY + 18);
        finalY += (splitText.length * 5) + 20;
    }

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Recommendation: Review High-Risk items against the Hydro-Immunity Protocol.', 14, finalY + 10);

    addFooter(doc);
    doc.save(`AnoHUB_Risk_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};

// --- 3. HPP CALCULATION REPORT ---
export const generateCalculationReport = (
    settings: HPPSettings,
    calculations: { powerMW: string, annualGWh: string, n_sq: string },
    recommendations: TurbineRecommendation[]
) => {
    const doc = new jsPDF();
    let startY = addHeader(doc, 'HYDROPOWER DESIGN REPORT');

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('1. Design Parameters (Inputs)', 14, startY);
    
    const inputData = [
        ['Net Head (H)', `${settings.head} m`],
        ['Flow Rate (Q)', `${settings.flow} m3/s`],
        ['Turbine Efficiency', `${settings.efficiency}%`],
        ['Hydrology Type', settings.flowVariation.toUpperCase()],
        ['Water Quality', settings.waterQuality.toUpperCase()]
    ];

    autoTable(doc, {
        startY: startY + 5,
        head: [['Parameter', 'Value']],
        body: inputData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
    });

    let currentY = (doc as any).lastAutoTable?.finalY + 15;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('2. Physics & Output Analysis', 14, currentY);

    const physicsData = [
        ['Installed Capacity (P)', `${calculations.powerMW} MW`],
        ['Annual Production (Est.)', `${calculations.annualGWh} GWh/year`],
        ['Specific Speed Index (n_sq)', `${calculations.n_sq} (Topology Factor)`]
    ];

    autoTable(doc, {
        startY: currentY + 5,
        head: [['Metric', 'Calculated Result']],
        body: physicsData,
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42], textColor: [6, 182, 212] },
        styles: { fontSize: 11, fontStyle: 'bold' }
    });

    currentY = (doc as any).lastAutoTable?.finalY + 15;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('3. Engineering Selection (Ranked)', 14, currentY);

    const recRows: any[] = [];
    recommendations.forEach((rec, index) => {
        const rank = index + 1;
        const status = rec.isBest ? 'OPTIMAL MATCH' : (rec.score > 0 ? 'Viable' : 'Not Recommended');
        const reasons = rec.reasons.map(r => r.replace('+', 'PRO: ').replace('-', 'CON: ')).join('\n');
        
        recRows.push([
            `#${rank} ${rec.key.toUpperCase()}`,
            status,
            reasons
        ]);
    });

    autoTable(doc, {
        startY: currentY + 5,
        head: [['Turbine Type', 'Suitability', 'Engineering Justification']],
        body: recRows,
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212], textColor: [255, 255, 255] },
        columnStyles: { 
            0: { fontStyle: 'bold', cellWidth: 30 },
            1: { fontStyle: 'bold', cellWidth: 30 },
            2: { fontSize: 9 } 
        },
        didParseCell: function(data) {
            if (data.column.index === 1 && data.cell.raw === 'OPTIMAL MATCH') {
                data.cell.styles.textColor = [22, 163, 74]; 
            }
        }
    });

    addFooter(doc);
    doc.save(`AnoHUB_Design_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};

// --- 4. FINANCIAL KPI REPORT ---
export const generateFinancialReport = (
    inputs: { capex: number; opex: number; price: number },
    baseKPI: { irr: string; npv: string; payback: string },
    riskKPI: { irr: string; npv: string; payback: string; penalty: string }
) => {
    const doc = new jsPDF();
    let startY = addHeader(doc, 'INVESTOR BRIEFING: KPI & RISK ANALYSIS');

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('1. Financial Assumptions (Inputs)', 14, startY);

    const inputRows = [
        ['CAPEX (Est.)', `€ ${inputs.capex.toLocaleString()}`],
        ['OPEX (Annual)', `€ ${inputs.opex.toLocaleString()}`],
        ['Energy Price', `€ ${inputs.price} / MWh`]
    ];

    autoTable(doc, {
        startY: startY + 5,
        head: [['Category', 'Value']],
        body: inputRows,
        theme: 'plain',
        styles: { fontSize: 10 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } }
    });

    let currentY = (doc as any).lastAutoTable?.finalY + 15;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('2. Risk Impact Analysis (The Execution Gap)', 14, currentY);
    
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('Comparison of returns: Ideal Scenario vs. Reality with "Standard" Execution.', 14, currentY + 5);

    const kpiRows = [
        ['IRR (Internal Rate of Return)', `${baseKPI.irr}%`, `${riskKPI.irr}%`, `-${(parseFloat(baseKPI.irr) - parseFloat(riskKPI.irr)).toFixed(1)}%`],
        ['NPV (Net Present Value)', `€ ${baseKPI.npv}M`, `€ ${riskKPI.npv}M`, `€ -${(parseFloat(baseKPI.npv) - parseFloat(riskKPI.npv)).toFixed(2)}M`],
        ['Payback Period', `${baseKPI.payback} Years`, `${riskKPI.payback} Years`, `+${(parseFloat(riskKPI.payback) - parseFloat(baseKPI.payback)).toFixed(1)} Years`]
    ];

    autoTable(doc, {
        startY: currentY + 10,
        head: [['KPI Metric', 'Ideal Target', 'Risk-Adjusted (Real)', 'Net Impact (Loss)']],
        body: kpiRows,
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
        columnStyles: { 
            0: { fontStyle: 'bold', cellWidth: 60 },
            3: { fontStyle: 'bold', textColor: [220, 38, 38] } 
        }
    });

    currentY = (doc as any).lastAutoTable?.finalY + 15;

    doc.setFillColor(240, 253, 250); 
    doc.roundedRect(14, currentY, 180, 35, 3, 3, 'F');
    
    doc.setFontSize(11);
    doc.setTextColor(6, 182, 212);
    doc.text('STRATEGIC RECOMMENDATION', 20, currentY + 10);
    
    doc.setFontSize(10);
    doc.setTextColor(50);
    const conclusion = `The analysis shows a potential value leakage of €${riskKPI.penalty} over the project lifecycle due to the Execution Gap. Implementing the AnoHUB Standard of Excellence (0.05 mm/m precision) is projected to recover approx. 85% of this risk-adjusted loss.`;
    const splitConclusion = doc.splitTextToSize(conclusion, 170);
    doc.text(splitConclusion, 20, currentY + 20);

    addFooter(doc);
    doc.save(`AnoHUB_Investor_Briefing_${new Date().toISOString().slice(0,10)}.pdf`);
};