// src/utils/pdfGenerator.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { VerificationData, ProtocolSection } from '../types';

export const generateInstallationReport = (
    progress: Record<string, VerificationData>,
    riskScore: number,
    protocols: ProtocolSection[]
) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();

    // --- HEADER ---
    doc.setFontSize(22);
    doc.setTextColor(6, 182, 212); // AnoHUB Cyan
    doc.text('AnoHUB', 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Strategic Risk Mitigation & Asset Integrity', 14, 25);

    doc.setDrawColor(6, 182, 212);
    doc.line(14, 28, 196, 28); // Horizontal line

    // --- TITLE & METADATA ---
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text('INSTALLATION VERIFICATION REPORT', 14, 40);

    doc.setFontSize(11);
    doc.text(`Date: ${date} ${time}`, 14, 48);
    
    // Risk Score Indicator
    doc.text('Discipline Risk Score:', 14, 55);
    doc.setFontSize(14);
    if (riskScore > 0) {
        doc.setTextColor(220, 38, 38); // Red
        doc.text(`${riskScore} (CRITICAL RISK)`, 60, 55);
    } else {
        doc.setTextColor(22, 163, 74); // Green
        doc.text(`${riskScore} (OPTIMAL)`, 60, 55);
    }

    // --- DATA PREPARATION ---
    // Moramo spojiti podatke iz 'progress' (vrijednosti) sa 'protocols' (naslovi koraka)
    const tableRows: any[] = [];

    protocols.forEach(section => {
        section.steps.forEach(step => {
            const data = progress[step.id];
            if (data) {
                tableRows.push([
                    step.id,
                    step.title,
                    data.status.toUpperCase(),
                    data.value || '-',
                    data.comment || '-',
                    data.logbookConfirmed ? 'YES' : 'NO'
                ]);
            }
        });
    });

    if (tableRows.length === 0) {
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text('No verification data recorded.', 14, 70);
    } else {
        // --- TABLE GENERATION ---
        autoTable(doc, {
            startY: 65,
            head: [['ID', 'Protocol Step', 'Status', 'Value', 'Observation', 'Logbook']],
            body: tableRows,
            theme: 'grid',
            headStyles: { 
                fillColor: [15, 23, 42], // Slate 900
                textColor: [6, 182, 212], // Cyan
                fontStyle: 'bold'
            },
            styles: {
                fontSize: 9,
                cellPadding: 3,
            },
            columnStyles: {
                0: { cellWidth: 15 }, // ID
                2: { cellWidth: 20, fontStyle: 'bold' }, // Status
                5: { cellWidth: 15 } // Logbook
            },
            didParseCell: function(data) {
                // Color coding for status
                if (data.section === 'body' && data.column.index === 2) {
                    const text = data.cell.raw as string;
                    if (text === 'FAILED') {
                        data.cell.styles.textColor = [220, 38, 38];
                    } else if (text === 'VERIFIED') {
                        data.cell.styles.textColor = [22, 163, 74];
                    }
                }
            }
        });
    }

    // --- FOOTER & SIGNATURE ---
    const finalY = (doc as any).lastAutoTable.finalY || 70;
    
    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.text('Verified by (Signature): __________________________', 14, finalY + 30);
    
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('This document certifies the execution status of the installation protocol.', 14, finalY + 45);
    doc.text('Generated by AnoHUB Platform - Hydro-Immunity Protocol.', 14, finalY + 50);

    // --- SAVE ---
    doc.save(`AnoHUB_Install_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};