export interface TurbineComponent {
    name: string;
    description: string;
    criticality: 'High' | 'Medium' | 'Low';
}

export interface TurbineDetail {
    name: string;
    mechanical: TurbineComponent[];
    electrical: TurbineComponent[];
}

export const turbineDetailData: Record<string, TurbineDetail> = {
    kaplan: {
        name: 'Kaplan Turbine',
        mechanical: [
            { name: 'Runner with Adjustable Blades', description: 'The main component enabling high efficiency at variable flows by adjusting blade angle.', criticality: 'High' },
            { name: 'Blade Adjustment Mechanism', description: 'The hydraulic system inside the runner hub that controls the blades. Requires precise sealing.', criticality: 'High' },
            { name: 'Wicket Gate (Guide Vanes)', description: 'Adjustable vanes that regulate water flow towards the runner.', criticality: 'High' },
            { name: 'Draft Tube', description: 'Increases the usable head by recovering kinetic energy at the runner outlet.', criticality: 'Medium' },
            { name: 'Thrust and Guide Bearings', description: 'Support the heavy rotating assembly and transmit axial and radial forces.', criticality: 'High' },
        ],
        electrical: [
            { name: 'Generator (Low-Speed)', description: 'Large-diameter synchronous generator designed for low rotational speeds, often directly coupled.', criticality: 'High' },
            { name: 'Excitation System', description: 'Provides direct current for the generator\'s magnetic field.', criticality: 'Medium' },
            { name: 'Speed and Power Governor', description: 'Controls the blade adjustment mechanism and wicket gate to maintain set speed and power.', criticality: 'High' },
            { name: 'Generator Cooling System', description: 'Typically air or water cooling to dissipate heat from the windings.', criticality: 'Medium' },
        ],
    },
    francis: {
        name: 'Francis Turbine',
        mechanical: [
            { name: 'Runner with Fixed Blades', description: 'A robust runner designed for a specific best efficiency point. Sensitive to off-design operation.', criticality: 'High' },
            { name: 'Spiral Casing', description: 'Directs water evenly around the circumference of the wicket gate, ensuring stable inflow.', criticality: 'Medium' },
            { name: 'Wicket Gate (Guide Vanes)', description: 'The main regulating element that controls the flow and power of the turbine.', criticality: 'High' },
            { name: 'Shaft Seal', description: 'Prevents high-pressure water from leaking along the shaft. Critical for reliability.', criticality: 'High' },
            { name: 'Thrust Bearing', description: 'Absorbs the immense axial forces generated by water flow through the runner.', criticality: 'High' },
        ],
        electrical: [
            { name: 'Generator (Medium-Speed)', description: 'Synchronous generator adapted to higher rotational speeds compared to Kaplan turbines.', criticality: 'High' },
            { name: 'Protection Relays', description: 'Protect the generator from overloads, short circuits, and other electrical faults.', criticality: 'High' },
            { name: 'Step-Up Transformer', description: 'Increases the generator voltage to a level suitable for power transmission.', criticality: 'Medium' },
            { name: 'SCADA System', description: 'Supervises and controls all aspects of plant operation, from the turbine to the switchyard.', criticality: 'High' },
        ],
    },
    pelton: {
        name: 'Pelton Turbine',
        mechanical: [
            { name: 'Runner with Buckets', description: 'A disc with double-lobed buckets that receive a high-pressure water jet. Prone to material fatigue.', criticality: 'High' },
            { name: 'Nozzles and Needles', description: 'Precisely control the flow and shape of the water jet. Needle wear reduces efficiency.', criticality: 'High' },
            { name: 'Jet Deflector', description: 'In emergencies, quickly diverts the jet from the runner to prevent an uncontrolled speed increase (overspeed).', criticality: 'High' },
            { name: 'Turbine Housing', description: 'Protects against water splash and directs water to the tailrace channel. It is not pressurized.', criticality: 'Low' },
            { name: 'Braking System', description: 'Used to bring the runner to a stop after the nozzles are closed.', criticality: 'Medium' },
        ],
        electrical: [
            { name: 'Generator (High-Speed)', description: 'Often a four-pole or two-pole synchronous generator for high rotational speeds, sometimes connected via a gearbox.', criticality: 'High' },
            { name: 'Overspeed Protection System', description: 'An independent system that activates deflectors and closes nozzles upon detecting excessive speed.', criticality: 'High' },
            { name: 'Switchgear', description: 'Circuit breakers and switches for safely connecting and disconnecting the generator from the grid.', criticality: 'Medium' },
            { name: 'Auxiliary Power System (UPS)', description: 'Ensures power for control and protection systems in case of a grid outage.', criticality: 'Medium' },
        ],
    },
    crossflow: {
        name: 'Crossflow Turbine',
        mechanical: [
            { name: 'Cylindrical Runner (C-shaped blades)', description: 'A simple and robust runner that allows water to pass through the blades twice.', criticality: 'High' },
            { name: 'Rectangular Nozzle with Regulating Vane', description: 'A simple mechanism for regulating flow by dividing the inlet opening.', criticality: 'Medium' },
            { name: 'Housing', description: 'A simple structure that directs water and prevents splashing.', criticality: 'Low' },
            { name: 'Standard Bearings', description: 'Standard industrial rolling-element bearings are often used, simplifying maintenance.', criticality: 'Medium' },
        ],
        electrical: [
            { name: 'Asynchronous (Induction) Generator', description: 'Often used due to its simplicity, robustness, and lower cost. May require reactive power compensation.', criticality: 'High' },
            { name: 'Control Panel', description: 'A basic system for starting, stopping, and protecting the generator.', criticality: 'Medium' },
            { name: 'Grid Protection', description: 'Relays that protect against islanding, undervoltage, and overvoltage.', criticality: 'High' },
        ],
    },
    "flow_through": {
        name: 'Run-of-River Turbine',
        mechanical: [
            { name: 'Axial Runner', description: 'Similar to a Kaplan runner, but often with fixed or limited-adjustment blades for operation in a narrow flow range.', criticality: 'High' },
            { name: 'Bulb or Pit Casing', description: 'Integrates the turbine and generator into a single, hydrodynamically optimized unit within the water flow.', criticality: 'High' },
            { name: 'Sealing Systems', description: 'Highly critical systems that protect the generator and bearings from water ingress.', criticality: 'High' },
            { name: 'Trash Rack', description: 'Essential for preventing large debris from entering the turbine, which could cause major damage.', criticality: 'Medium' },
        ],
        electrical: [
            { name: 'Submerged Generator', description: 'A specially designed generator for operation inside a watertight casing (Bulb or Pit), requiring efficient cooling.', criticality: 'High' },
            { name: 'Planetary Gearbox (if used)', description: 'Increases the turbine\'s rotational speed to a speed suitable for a standard, faster generator.', criticality: 'High' },
            { name: 'Condition Monitoring System (CMS)', description: 'Monitors vibrations, temperatures, and leakage to enable predictive maintenance.', criticality: 'Medium' },
            { name: 'Submarine Cables', description: 'High-voltage cables for transmitting power from the submerged generator to the shore.', criticality: 'Medium' },
        ],
    },
};