import { writeFile } from 'node:fs/promises';
import { jsPDF } from 'jspdf';

type CertificateData = {
  projectName: string;
  testsPassed: number;
  testsTotal: number;
  certifiedModules: string[];
  deploymentUrls: string[];
  issuedAtIso: string;
};

const data: CertificateData = {
  projectName: 'anohub-hpp-risk-excellence-platform',
  testsPassed: 252,
  testsTotal: 252,
  certifiedModules: [
    'Certified Forensic Module: VibrationForensics — 2014 Cavitation (120Hz / 240Hz)'
  ],
  deploymentUrls: [
    'https://app.anohubs.com',
    'https://anohubsapp-lfdpbdzas-anohubs-projects.vercel.app'
  ],
  issuedAtIso: new Date().toISOString()
};

const doc = new jsPDF({ unit: 'pt', format: 'a4' });

const pageWidth = doc.internal.pageSize.getWidth();
const margin = 48;
let y = 72;

doc.setFillColor(2, 6, 23);
doc.rect(0, 0, pageWidth, 120, 'F');

doc.setTextColor(255, 255, 255);
doc.setFont('helvetica', 'bold');
doc.setFontSize(20);
doc.text('Final System Integrity Certificate', margin, 62);

doc.setFont('helvetica', 'normal');
doc.setFontSize(11);
doc.text(`Issued: ${data.issuedAtIso}`, margin, 92);

doc.setTextColor(15, 23, 42);
doc.setFont('helvetica', 'bold');
doc.setFontSize(14);
y = 160;
doc.text('System Status', margin, y);

doc.setFont('helvetica', 'normal');
doc.setFontSize(12);
y += 22;
doc.text(`Project: ${data.projectName}`, margin, y);
y += 18;
doc.text(`Test Suite: ${data.testsPassed}/${data.testsTotal} passing`, margin, y);

doc.setFont('helvetica', 'bold');
doc.setFontSize(14);
y += 34;
doc.text('Certifications', margin, y);

doc.setFont('helvetica', 'normal');
doc.setFontSize(12);
y += 22;
for (const line of data.certifiedModules) {
  const wrapped = doc.splitTextToSize(line, pageWidth - margin * 2);
  doc.text(wrapped, margin, y);
  y += wrapped.length * 16 + 6;
}

doc.setFont('helvetica', 'bold');
doc.setFontSize(14);
y += 18;
doc.text('Deployment', margin, y);

doc.setFont('helvetica', 'normal');
doc.setFontSize(12);
y += 22;
for (const url of data.deploymentUrls) {
  doc.setTextColor(37, 99, 235);
  doc.textWithLink(url, margin, y, { url });
  doc.setTextColor(15, 23, 42);
  y += 18;
}

doc.setDrawColor(148, 163, 184);
doc.setLineWidth(1);
doc.line(margin, 760, pageWidth - margin, 760);

doc.setFont('helvetica', 'normal');
doc.setFontSize(10);
doc.setTextColor(51, 65, 85);
doc.text('Certificate generated by CI-assist tooling.', margin, 786);

const bytes = doc.output('arraybuffer');
await writeFile('Final-System-Integrity-Certificate.pdf', Buffer.from(bytes));

console.log('Wrote Final-System-Integrity-Certificate.pdf');
