import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const glossaryPath = path.join(__dirname, '../docs/GLOSSARY.md');
const outputPath = path.join(__dirname, '../src/data/GlossaryDefinitions.ts');

try {
    const content = fs.readFileSync(glossaryPath, 'utf8');
    const lines = content.split('\n');
    
    const definitions = {};
    let isInTable = false;

    lines.forEach(line => {
        if (line.trim().startsWith('|') && line.includes('Term') && line.includes('Definition')) {
            isInTable = true;
            return;
        }
        if (line.trim().startsWith('|') && line.includes('---')) {
            return;
        }

        if (isInTable && line.trim().startsWith('|')) {
            const parts = line.split('|').map(p => p.trim()).filter(p => p !== '');
            if (parts.length >= 2) {
                // Term is often bolded like **Hoop Stress**
                const rawTerm = parts[0].replace(/\*\*/g, '').trim();
                const definition = parts[1].trim();
                const reference = parts.length > 2 ? parts[2] : '';
                
                // Extract clean link from reference if exists [Name](path)
                const linkMatch = reference.match(/\[(.*?)\]\((.*?)\)/);
                const codeRef = linkMatch ? { name: linkMatch[1], path: linkMatch[2] } : null;

                definitions[rawTerm] = {
                    definition,
                    codeRef
                };
            }
        }
    });

    const fileContent = `// Generated by scripts/sync_glossary.mjs
// Do not edit directly. Update docs/GLOSSARY.md instead.

export interface GlossaryEntry {
    definition: string;
    codeRef?: { name: string; path: string } | null;
}

export const GLOSSARY: Record<string, GlossaryEntry> = ${JSON.stringify(definitions, null, 4)};
`;

    fs.writeFileSync(outputPath, fileContent);
    console.log(`Glossary synced to ${outputPath}. Found ${Object.keys(definitions).length} entries.`);

} catch (err) {
    console.error('Failed to sync glossary:', err);
    process.exit(1);
}
