-- Sovereign Database Schema (NC-11200)
-- Reference for: dynamic_sensor_data, telemetry_logs, work_orders, expert_knowledge_base

-- ============================================================================
-- 1. TELEMETRY LOGS (Time-Series)
-- Optimized for high-frequency writes and time-range queries.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id text NOT NULL,
  details jsonb, -- Flexible payload for specific sensor readings
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS telemetry_logs_asset_time_idx ON public.telemetry_logs (asset_id, created_at DESC);
CREATE INDEX IF NOT EXISTS telemetry_logs_created_at_idx ON public.telemetry_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS telemetry_logs_details_gin ON public.telemetry_logs USING GIN (details);

-- ============================================================================
-- 2. DYNAMIC SENSOR DATA (Real-Time Buffer)
-- Used for the latest state ingestion before archival.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.dynamic_sensor_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id text NOT NULL,
  timestamp timestamptz NOT NULL,
  output_power numeric,
  francis_data jsonb, -- Specific hydraulic data
  created_at timestamptz DEFAULT now(),
  UNIQUE(asset_id, timestamp) -- Prevent duplicate time points
);

CREATE INDEX IF NOT EXISTS dynamic_sensor_data_asset_idx ON public.dynamic_sensor_data (asset_id);
CREATE INDEX IF NOT EXISTS dynamic_sensor_data_time_idx ON public.dynamic_sensor_data (timestamp DESC);

-- ============================================================================
-- 3. TELEMETRY HISTORY CACHE
-- Stores aggregated or processed history for fast client retrieval.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.telemetry_history_cache (
  asset_id text PRIMARY KEY,
  history jsonb, -- Array of aggregated points
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS telemetry_history_cache_updated_at_idx ON public.telemetry_history_cache (updated_at DESC);

-- ============================================================================
-- 4. WORK ORDERS (Maintenance & Alerts)
-- Generated by Autonomous Alerts or Manual Operators.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.work_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id text NOT NULL,
  title text NOT NULL,
  issue_type text, -- e.g. 'VIBRATION_HIGH', 'EROSION_DETECTED'
  status text DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================================
-- 5. EXPERT KNOWLEDGE BASE
-- Lookup table for autonomous diagnosis rules.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.expert_knowledge_base (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  symptom_key text UNIQUE NOT NULL, -- e.g. 'HIGH_VIBRATION'
  recommended_action text NOT NULL, -- e.g. 'INSPECT_BEARING'
  confidence_score numeric DEFAULT 1.0
);

-- ============================================================================
-- 6. TRIGGERS & FUNCTIONS
-- ============================================================================

-- Autonomous Alerts Function
CREATE OR REPLACE FUNCTION public.autonomous_alerts_fn()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vib NUMERIC := NULL;
    symptom TEXT := NULL;
    ek RECORD;
    existing_count INT := 0;
    VIB_THRESHOLD NUMERIC := 5;
BEGIN
    -- [Logic omitted for brevity - see scripts/autonomous_alerts.sql for full implementation]
    RETURN NEW;
END;
$$;

-- Note: Triggers must be attached manually or via migration scripts.
