// Generated by scripts/sync_glossary.mjs
// Do not edit directly. Update docs/GLOSSARY.md instead.

export interface GlossaryEntry {
    definition: string;
    codeRef?: { name: string; path: string } | null;
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
    "Hoop Stress": {
        "definition": "The circumferential stress in a cylinder caused by internal pressure ($\\sigma_h = \\frac{P \\cdot D}{2t}$). If it exceeds yield strength, pipe bursts.",
        "codeRef": {
            "name": "PhysicsEngine.ts",
            "path": "../src/core/PhysicsEngine.ts"
        }
    },
    "Water Hammer": {
        "definition": "Pressure surge caused by sudden flow stoppage ($\\Delta P = \\rho \\cdot a \\cdot \\Delta v$). Joukowski Equation.",
        "codeRef": {
            "name": "WaterHammer.tsx",
            "path": "../src/components/francis/WaterHammer.tsx"
        }
    },
    "Resonance": {
        "definition": "Oscillation amplitude spike at specific frequencies (e.g., Runaway Speed).",
        "codeRef": {
            "name": "VibrationBaseline.ts",
            "path": "../src/services/VibrationBaseline.ts"
        }
    },
    "Erosion": {
        "definition": "Mechanical wear from abrasive particles ($E \\propto v^3 \\cdot C$).",
        "codeRef": {
            "name": "SandErosionTracker.ts",
            "path": "../src/services/SandErosionTracker.ts"
        }
    },
    "Cavitation": {
        "definition": "Vapor bubble collapse causing pitting. Occurs when local pressure drops below vapor pressure.",
        "codeRef": {
            "name": "HydraulicLimits.ts",
            "path": "../src/services/HydraulicLimits.ts"
        }
    },
    "Runaway Speed": {
        "definition": "The maximum speed a turbine reaches at full flow with no load. A critical structural limit.",
        "codeRef": {
            "name": "SafetyInterlockEngine.ts",
            "path": "../src/services/SafetyInterlockEngine.ts"
        }
    },
    "NPSH": {
        "definition": "Net Positive Suction Head ($NPSH = \\frac{P_{atm} - P_v}{\\rho g} - \\Delta h_s$). Margin against cavitation.",
        "codeRef": {
            "name": "HydraulicLimits.ts",
            "path": "../src/services/HydraulicLimits.ts"
        }
    },
    "Joukowski Surge": {
        "definition": "Theoretical maximum pressure rise during instantaneous valve closure. See Water Hammer.",
        "codeRef": {
            "name": "WaterHammer.tsx",
            "path": "../src/components/francis/WaterHammer.tsx"
        }
    },
    "Erosion Rate": {
        "definition": "The speed of material loss ($\\mu m/year$), driven by sediment hardness and velocity cubed.",
        "codeRef": {
            "name": "SandErosionTracker.ts",
            "path": "../src/services/SandErosionTracker.ts"
        }
    },
    "Specific Speed": {
        "definition": "Dimensionless index ($n_s = \\frac{n \\sqrt{P}}{H^{5/4}}$) used to classify turbine geometry (Pelton vs Francis vs Kaplan).",
        "codeRef": {
            "name": "UnifiedPhysicsCore.ts",
            "path": "../src/features/physics-core/UnifiedPhysicsCore.ts"
        }
    }
};
